# Generated by Django 3.1.7 on 2022-06-28 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cde_process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcnn',
            name='process_id',
        ),
        migrations.AddField(
            model_name='addcnn',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
