# Generated by Django 3.1.7 on 2022-06-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cde_process', '0002_auto_20220628_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcnn',
            name='username',
        ),
    ]
