# Generated by Django 3.1.7 on 2022-06-28 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cde_process', '0003_remove_addcnn_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcnn',
            name='sample_file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
