# Generated by Django 3.1.7 on 2022-06-28 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cde_process', '0004_auto_20220628_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=30)),
                ('attribute_type', models.CharField(choices=[('key_item', 'key_item'), ('line_item', 'line_item')], max_length=30)),
                ('attribute_cs', models.CharField(max_length=30)),
                ('is_derived', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=30)),
                ('min_lenght', models.IntegerField()),
                ('max_lenght', models.IntegerField()),
                ('Zone', models.CharField(choices=[('unknown', 'Unknown'), ('top', 'top'), ('top_right', 'top_right'), ('center', 'center'), ('bootom_left', 'bootom_left'), ('bootom_right', 'bootom_right'), ('bootom', 'bootom'), ('page', 'page')], max_length=30)),
                ('default_value', models.CharField(max_length=30)),
                ('required_in_qc', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=30)),
                ('required_in_output', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=30)),
                ('mandate', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=30)),
                ('data_label', models.FileField(upload_to='media/data_label')),
                ('value_type', models.CharField(choices=[('string', 'string')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='addcnn',
            name='sample_file',
            field=models.FileField(blank=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['.zip'])]),
        ),
    ]
