# Generated by Django 3.1.7 on 2022-06-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cde_process', '0005_auto_20220628_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCnn',
            new_name='AddCnnModel',
        ),
        migrations.RenameField(
            model_name='manageattribute',
            old_name='max_lenght',
            new_name='max_length',
        ),
        migrations.RenameField(
            model_name='manageattribute',
            old_name='min_lenght',
            new_name='min_length',
        ),
    ]
