# Generated by Django 3.1.7 on 2022-06-24 06:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=30)),
                ('pipeline', models.CharField(choices=[('Engine-I', 'Engine-I'), ('Engine-II', 'Engine-II')], max_length=30, null=True)),
                ('classification_model', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=30, null=True)),
                ('input_document', multiselectfield.db.fields.MultiSelectField(choices=[('JPG', 'JPG'), ('PDF', 'PDF'), ('JPEG', 'JPEG'), ('TIF', 'TIF'), ('PNG', 'PNG')], max_length=20, null=True)),
                ('time_zone', models.CharField(choices=[(0, '(UTC-12:00)Universal Coordinated Time GMT '), (1, '(EET) Eastern European Time GMT+2:00'), (2, '(IST) India Standard Time\tGMT+5:30')], max_length=30, null=True)),
                ('process_sla', models.CharField(choices=[(0, '1 hours'), (1, '2 hours'), (2, '3 hours'), (3, '4 hours'), (4, '5 hours'), (5, '6 hours'), (6, '7 hours'), (7, '8 hours'), (8, '9 hours'), (9, '10 hours'), (10, '11 hours'), (11, '12 hours'), (12, '13 hours'), (13, '14 hours'), (14, '15 hours'), (15, '16 hours'), (16, '17 hours'), (17, '18 hours'), (18, '19 hours'), (19, '20 hours'), (20, '21 hours'), (21, '22 hours'), (22, '23 hours'), (23, '24 hours')], max_length=30, null=True)),
                ('pre_processing', models.CharField(choices=[(0, 'no'), (1, 'yes')], max_length=30, null=True)),
            ],
        ),
    ]
