# Generated by Django 3.1.7 on 2022-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cde', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprocess',
            name='pipeline',
            field=models.CharField(choices=[(0, 'Engine-I'), (1, 'Engine-II')], max_length=30),
        ),
    ]
