# Generated by Django 3.1.7 on 2022-06-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cde', '0002_auto_20220624_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprocess',
            name='pre_processing',
            field=models.CharField(blank=True, choices=[('0', 'no'), ('1', 'yes')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newprocess',
            name='process_sla',
            field=models.CharField(blank=True, choices=[('0', '1 hours'), ('1', '2 hours'), ('2', '3 hours'), ('3', '4 hours'), ('4', '5 hours'), ('5', '6 hours'), ('6', '7 hours'), ('7', '8 hours'), ('8', '9 hours'), ('9', '10 hours'), ('10', '11 hours'), ('11', '12 hours'), ('12', '13 hours'), ('13', '14 hours'), ('14', '15 hours'), ('15', '16 hours'), ('16', '17 hours'), ('17', '18 hours'), ('18', '19 hours'), ('19', '20 hours'), ('20', '21 hours'), ('21', '22 hours'), ('22', '23 hours'), ('23', '24 hours')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newprocess',
            name='time_zone',
            field=models.CharField(blank=True, choices=[('0', '(UTC-12:00)Universal Coordinated Time GMT'), ('1', '(EET) Eastern European Time GMT+2:00'), ('2', '(IST) India Standard Time\tGMT+5:30')], max_length=30, null=True),
        ),
    ]
