# Generated by Django 3.1.7 on 2022-06-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cde', '0003_auto_20220624_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular model', 'Regular Model'), ('vgg16 model', 'Vgg16 Model')], max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('confidence_threshold', models.IntegerField(max_length=30)),
                ('sample_file', models.FileField(upload_to='')),
                ('epochs', models.CharField(choices=[('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=30)),
                ('batch_size', models.CharField(choices=[('16', '16'), ('32', '32'), ('64', '64')], max_length=30)),
                ('kernal_initializer', models.CharField(choices=[('he_normal', 'he_normal'), ('he_uniform', 'he_uniform')], max_length=30)),
                ('optimizer', models.CharField(choices=[('adam', 'adam'), ('sgd', 'sgd'), ('rmsprop', 'rmsprop')], max_length=30)),
                ('test_size', models.CharField(choices=[('0.3', '0.3'), ('0.15', '0.15'), ('0.18', '0.18'), ('0.21', '0.21'), ('0.24', '0.24'), ('0.27', '0.27')], max_length=30)),
                ('activation', models.CharField(choices=[('relu', 'relu'), ('leaky relu', 'leaky relu')], max_length=30)),
            ],
        ),
    ]
