# Generated by Django 3.1.7 on 2022-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cde', '0004_auto_20220623_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprocess',
            name='classification_model',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=30, null=True),
        ),
    ]
