# Generated by Django 3.1.7 on 2022-06-23 12:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cde', '0005_auto_20220623_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprocess',
            name='input_document',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('JPG', 'JPG'), ('PDF', 'PDF'), ('JPEG', 'JPEG'), ('TIF', 'TIF'), ('PNG', 'PNG')], max_length=20, null=True),
        ),
    ]
