name: Create tag
on:
  push:
    branches: "main"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: sourav-crossml/full_stack_training@latest
        with:
          tag: "latest"
          message: "Latest release"
