name: Create/update tag
on:
  pull_request:
    branches: "main"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sourav-crossml/full_stack_training@v1
        with:
          tag: "latest@v0.0.1"
          message: "Latest release"
