name: auto_tag
on:
  pull_request:
    branches:
      - main
jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag and push current repo code
        run: |
          git tag ${{github.run_id}}
          git push origin ${{github.run_id}}
